# join the resulting package in a new image (https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#join) 
# 
# See also https://github.com/rancher-sandbox/cos-toolkit-sample-repo/commit/1e9e33a7feb600ecef5948d137659f95e8e31b0b
# for an equivalent using a different strategy
requires:
- category: "system"
  name: "cos"
  version: ">=0"
- category: "app"
  name: "sampleOSService"
  version: ">=0"
- category: "selinux"
  name: "policy"
  version: ">=0"

requires_final_images: true
# Run the steps in the resulting container
steps:
- sed -i 's/:VERSION:/{{.Values.version}}/g' setup.yaml
- sed -i 's/:PRETTY_NAME:/{{.Values.brand_name}} v{{.Values.version}}/g' setup.yaml
- cp -fv 02_upgrades.yaml /system/oem/02_upgrades.yaml
- cp -fv 03_branding.yaml /system/oem/03_branding.yaml
- cp -fv 04_accounting.yaml /system/oem/04_accounting.yaml
- useradd --system dummyuser
- yip setup.yaml

# This tells luet to create a package from the resulting container content.
# The image will be squashed and unpacked
# See also: https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#unpack
unpack: true

# A regexp list of patterns
# to exclude from the resulting image
# See also: https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#excludes
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/root/.bash_history
- ^/run/reboot-needed
