requires:
- category: "system"
  name: "cos"
  version: ">=0"
copy:
- package:
    category: "app"
    name: "sampleOSService"
    version: ">=0"
  source: /usr/bin/sampleOSService
  destination: /usr/bin/sampleOSService
- package:
    category: "app"
    name: "sampleOSService"
    version: ">=0"
  source: /system/oem/10_sampleOSService.yaml
  destination: /system/oem/10_sampleOSService.yaml
   
steps:
- sed -i 's/:VERSION:/{{.Values.version}}/g' setup.yaml
- sed -i 's/:PRETTY_NAME:/{{.Values.brand_name}} v{{.Values.version}}/g' setup.yaml
- cp -fv 02_upgrades.yaml /system/oem/02_upgrades.yaml
- cp -fv 03_branding.yaml /system/oem/03_branding.yaml
- cp -fv 04_accounting.yaml /system/oem/04_accounting.yaml
- useradd --system dummyuser
- zypper in -y {{.Values.additional_packages}}
- yip setup.yaml

unpack: true
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/srv/.*
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm

- ^/usr/lib64/rpm-plugins
# Yast
- ^/var/lib/YaST2

# General
#- ^/usr/include
#- ^/usr/local
- ^/usr/local/bin
- ^/usr/local/go
- ^/usr/local/include
- ^/usr/local/lib.*
- ^/usr/local/man
- ^/usr/local/sbin
- ^/usr/local/share
- ^/usr/local/src
- ^/usr/local/games
