requires:
- name: "golang"
  category: "build"
  version: ">=0"

env:
- PATH=$PATH:/usr/local/go/bin
- GOPATH=/luetbuild/go

steps:
- zypper in -y {{.Values.additional_packages}}
- go build -o sampleOSService main.go 
- mv sampleOSService /usr/bin
- cp 10_sampleOSService.yaml /system/oem/
- useradd --system dummyuser
